<# 
.SYNOPSIS 
    Log parser for  logs generated by Loki 
.DESCRIPTION 
    Run as: 'Parse-LokiLog C:\loki.log'
.AUTHOR
    Vasken Houdoverdov
#>  

function Parse-LokiLog {
   Param([string]$Path)
	
$e = @();
$p = @();

gc $Path | % { if($_ -match 'Z (.+) LOKI: Yara Rule MATCH: (.+) TYPE: (.+) DESCRIPTION: (.+) FILE: (.+) FIRST_BYTES: (.+) MD5: ([a-f0-9]{32}) SHA1: ([0-9a-f]{40}) SHA256: ([A-Fa-f0-9]{64}) MATCHES: (.*)$') { 

$MatchProps = [Ordered]@{
Hostname =    $Matches[1]
RuleMatch =   $Matches[2]
Type =        $Matches[3]
Description = $Matches[4]
File =        $Matches[5]
FirstBytes =  $Matches[6]
MD5sum =      $Matches[7]
SHA1sum =     $Matches[8]
SHA256 =      $Matches[9]
Matches =     $Matches[10]
}

$e += $(New-Object PSObject -Property $MatchProps)
}}

gc $Path | % { if($_ -match 'Z (.+) LOKI: Listening process PID: (\d+) NAME: (.+) COMMAND: (.+) IP: (.+) PORT: (\d+)') { 

$MatchProps = [Ordered]@{
Hostname =    $Matches[1]
PID =         $Matches[2]
ProcessName = $Matches[3]
Command =     $Matches[4]
IP =          $Matches[5]
Port =        $Matches[6]
}

$p += $(New-Object PSObject -Property $MatchProps)
}}

$e | ConvertTo-Html -Head $(gc styles.css) -body "<h4>Loki Report (YARA Matches) - Generated on $(Get-Date) by $(whoami)</h4>" | Out-File .\Loki_YARA_Matches.html 
$p | ConvertTo-Html -Head $(gc styles.css) -body "<h4>Loki Report (Listening Processes) - Generated on $(Get-Date) by $(whoami)</h4>" | Out-File .\Loki_Listening.html 
}
